const Menu = [
    {
        id: 1,
        image: "image/noodles.jpg",
        name: "noodle",
        category: "lunch",
        price: 26,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 2,
        image: "image/pizza.jpg",
        name: "pizza",
        category: "evening",
        price: 120,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 3,
        image: "image/burger.jpg",
        name: "burger",
        category: "snack",
        price: 80,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 4,
        image: "image/pasta.jpg",
        name: "pasta",
        category: "dinner",
        price: 95,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 5,
        image: "image/sandwich.jpg",
        name: "sandwich",
        category: "breakfast",
        price: 45,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 6,
        image: "image/momos.jpg",
        name: "momos",
        category: "snack",
        price: 60,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 7,
        image: "image/friedrice.jpg",
        name: "fried rice",
        category: "lunch",
        price: 90,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 8,
        image: "image/coffee.jpg",
        name: "coffee",
        category: "drink",
        price: 30,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 9,
        image: "image/icecream.jpg",
        name: "ice cream",
        category: "dessert",
        price: 50,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
    {
        id: 10,
        image: "image/tea.jpg",
        name: "tea",
        category: "drink",
        price: 20,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste nulla saepe ipsam. Quam itaque aspernatur labore iste quo magnam harum ullam tempora aut.",
    },
];

export default Menu;